### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by theniwo** [piopi/docker-desktop#1]
Hi, great work. 
I have some suggestions, you and your recipients may like

* Run the whole thing as a normal user 
* Have a docker volume to store user settings, like 
```
-v docker_desktop_home:/home \
-v docker_desktop_root:/root \
```
* Give your container a name with `--name`
* why is chrome running in no sandbox mode?

Regards

**Comment by piopi** [comment]
Hi thank you for your suggestions, to answer your question:

1. Chrome needs to be run in a no sandbox mode because we are running the container as a root user but I will follow your suggestion and add a non-root user. Which will solve both of the issues. 
2.  For the other suggestions, I will add them to the readme of the project.  The user settings location on the container is already under `/root/.config`, so you can bind any volume from the host to it. 

Both those changes will come in the next version of the image.
Regards

**Comment by piopi** [comment]
Features implemented in the new versions, I removed chrome as a browser because it seems we can only use the --no-sandbox option when running it on a docker container. I replaced it with Firefox instead.
